#!/bin/bash

CURRENT_DIR=$(cd $(dirname $0); pwd)

PLATFORM=$(uname -m)

if [ "${PLATFORM}" == "x86_64" ]; then
    sudo ${CURRENT_DIR}/icesprog.x64.linux $@
elif [ "${PLATFORM}" == "Darwin" ]; then
    sudo ${CURRENT_DIR}/icesprog.x64.macos $@
elif [ "${PLATFORM}" == "aarch64" ]; then
    sudo ${CURRENT_DIR}/icesprog.aarch64 $@
else
    sudo ${CURRENT_DIR}/icesprog.arm $@
fi
